/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.ecomarket.view;

import ec.edu.espe.ecomarket.controller.FileManager;
import ec.edu.espe.ecomarket.model.Employee;
import ec.edu.espe.ecomarket.model.Manager;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.PasswordAuthentication;

/**
 *
 * @author Alex Trejo, PACSTORE, DCCO-ESPE
 */
public class FrmLoginManager extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLoginManager() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        pssd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEXANDER\\Desktop\\Alexander programa\\EcoMarket\\src\\main\\java\\ec\\edu\\espe\\ecomarket\\images\\flecha60x60.png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 330, 60, 60));

        btnEnter.setBackground(new java.awt.Color(102, 51, 0));
        btnEnter.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 130, 40));

        txtUserName.setBackground(java.awt.SystemColor.windowBorder);
        txtUserName.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 340, -1));

        pssd.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.hoverBackground"));
        getContentPane().add(pssd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 340, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEXANDER\\Desktop\\Alexander programa\\EcoMarket\\src\\main\\java\\ec\\edu\\espe\\ecomarket\\images\\LoginManager600x400.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FrmEmployeeOrManager login= new FrmEmployeeOrManager();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        int stateManager = 0;
        int stateEmployee = 0;
        Manager manager = new Manager();
        Employee employee = new Employee();

        manager.setUserName(txtUserName.getText());
        manager.setPassword(new String(pssd.getPassword()));

        System.out.println("pas-->"+manager.getPassword());
        System.out.println("nme->"+manager.getUserName());
        stateManager = FileManager.validateUserManager(manager);

        while (stateManager == 0) {

            stateManager = FileManager.validateUserManager(manager);

        }
        stateManager = FileManager.reenterManagerData(stateManager);

        if (stateManager != 0) {
            FrmActionsOfTheManager actionsManager = new FrmActionsOfTheManager();
            actionsManager.setVisible(true);
            this.setVisible(false);

        }
        /*

        employee.setName(txtUserName.getText());
        employee.setPassword(new String (pssd.getPassword()));
        stateEmployee= FileManager.validateUserEmployee(employee);

        while(stateEmployee==0){
            stateEmployee= FileManager.validateUserEmployee(employee);
            emptyFields();
        }

        stateEmployee=FileManager.validateUserEmployee(employee);

        if (stateEmployee!=0){
            FmrActionsOfTheEmployee actionsEmployee = new FmrActionsOfTheEmployee();
            actionsEmployee.setVisible(true);
            this.setVisible(false);

        }
        /*employee.setUserName(txtUserName.getText());
        employee.setPassword(pssd.getText());

        employee = FileManager.userLoginEmployee();
        stateEmployee = FileManager.validateUserEmployee(employee);

        employee = FileManager.reenterEmployeeData(stateEmployee);*/

    }//GEN-LAST:event_btnEnterActionPerformed

    private void emptyFields() {

        txtUserName.setText("");
        pssd.setText("");
    }
    /*public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("ec.edu.espe.ecomarket.images/Home75x75.png"));
        return retValue;
    
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pssd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
