/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.ecomarket.view;

/**
 *
 * @author Alex Trejo, PACSTORE, DCCO-ESPE
 */
public class FrmSubmission extends javax.swing.JFrame {

    /**
     * Creates new form FrmSubmission
     */
    public FrmSubmission() {
        initComponents();        
        this.setLocationRelativeTo(null);
        transparentButton(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEnter = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEnter.setBackground(new java.awt.Color(153, 51, 0));
        BtnEnter.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BtnEnter.setForeground(new java.awt.Color(255, 255, 255));
        BtnEnter.setText("INICIAR SESIÓN");
        BtnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEnterMouseExited(evt);
            }
        });
        BtnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnterActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, 30));

        btnExit.setBackground(new java.awt.Color(153, 51, 0));
        btnExit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("SALIR");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 255, 200, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEXANDER\\Desktop\\Alexander programa\\EcoMarket\\src\\main\\java\\ec\\edu\\espe\\ecomarket\\images\\Presentation600x400.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void BtnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnterActionPerformed
        // TODO add your handling code here:
        FrmEmployeeOrManager login= new FrmEmployeeOrManager();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnEnterActionPerformed

    private void BtnEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEnterMouseEntered
        // TODO add your handling code here:
        BtnEnter.setOpaque(true);
        BtnEnter.setContentAreaFilled(true);
        BtnEnter.setBorderPainted(true);
    }//GEN-LAST:event_BtnEnterMouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setOpaque(true);
        btnExit.setContentAreaFilled(true);
        btnExit.setBorderPainted(true);
    }//GEN-LAST:event_btnExitMouseEntered

    private void BtnEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEnterMouseExited
        // TODO add your handling code here:
                transparentButton(false);

    }//GEN-LAST:event_BtnEnterMouseExited

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
                transparentButton(false);

    }//GEN-LAST:event_btnExitMouseExited

    
    
    
    
     public void transparentButton(boolean button) {

        BtnEnter.setOpaque(button);
        BtnEnter.setContentAreaFilled(button);
        BtnEnter.setBorderPainted(button);

        btnExit.setOpaque(button);
        btnExit.setContentAreaFilled(button);
        btnExit.setBorderPainted(button);

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSubmission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnter;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
